site_name: FullProf
repo_url: https://pranabdas.github.io/
site_description: Tutorial for XRD peak fitting using FullProf.
site_author: Pranab Das

nav:
    - Table of Contents: index.md
    - Installation: install.md
    - Create PCR: create-pcr.md
    - Edit PCR: edit-pcr.md
    - Refinement: refinement.md

theme:
    name: null
    custom_dir: simplicity
    static_templates:
        - 404.html

    include_search_page: true
    search_index_only: false

    highlightjs: true

markdown_extensions:
    - pymdownx.arithmatex
    - attr_list

copyright: " "
# google_analytics: [UA-163317742-1, https://pranabdas.github.io/]
